algorithms:
- kmeans
- hierarchical
- dbscan
analyses:
- static
- dynamic
- combined
auto_tune_dbscan: true
comparison_mode: true
create_plots: true
dbscan_mode: hierarchical
hierarchical_mode: hierarchical
kmeans_mode: comparative
skip_preprocessing: false
