# ========================================
# CLUSTERING CONFIGURATION
# ========================================
# Kompakte, klare Konfiguration für 3-stufige Analyse

# ========================================
# CLUSTERING ALGORITHM
# ========================================
classification:
  algorithm: 'kmeans, hierarchical, dbscan'  # Verfügbar: kmeans, hierarchical, dbscan

  # K-Means spezifische Parameter
  kmeans:
    n_init: 20          # Anzahl Initialisierungen
    max_iter: 300       # Maximum Iterationen
    algorithm: 'lloyd'  # K-Means Algorithmus-Variante

  # Hierarchical Clustering Parameter
  hierarchical:
    linkage: 'ward'              # Linkage-Methode (ward, complete, average, single)
    distance_metric: 'euclidean' # Distanzmetrik (euclidean für ward erforderlich)

  # DBSCAN Parameter (Density-Based)
  dbscan:
    eps: 0.5           # Maximaler Abstand zwischen Punkten (kritischer Parameter!)
    min_samples: 5     # Minimale Anzahl Punkte für Core-Punkt
    metric: 'euclidean'  # Distanzmetrik
    # Hinweis: n_clusters wird automatisch gefunden
    # eps muss ggf. angepasst werden je nach Daten (typisch: 0.3-2.0)

# ========================================
# CLUSTER-ANZAHL
# ========================================
static_analysis:
  n_clusters: 5  # Empfohlen: 3-7

dynamic_analysis:
  n_clusters: 5
  min_years_required: 5  # Minimum Jahre pro Unternehmen

combined_analysis:
  n_clusters: 6
  weights:
    static: 0.4   # 40% Gewicht auf aktuellen Status
    dynamic: 0.6  # 60% Gewicht auf Entwicklung

# ========================================
# FEATURES
# ========================================
# Zwei Modi verfügbar:
# 1. Preset-Modus: Nutzt vordefinierte Feature-Sets aus features_config.yaml
# 2. Manual-Modus: Explizite Feature-Liste (wie bisher)

feature_selection:
  mode: 'preset'  # 'preset' oder 'manual'
  preset: 'pca_optimized'  # Wenn mode=preset: minimal, standard, comprehensive, pca_optimized

# ========================================
# MANUAL MODE FEATURES (wenn mode='manual')
# ========================================
static_analysis:
  features:
    # Profitability (erweitert)
    - roa
    - roe
    - ebit_margin
    - gross_margin
    - roc

    # Liquidity
    - current_ratio
    - working_capital_ratio

    # Leverage
    - debt_to_equity
    - equity_ratio
    - interest_coverage

    # Efficiency
    - asset_turnover
    - capital_intensity

    # Cashflow
    - fcf_margin
    - cash_conversion

    # Structure
    - financial_leverage

dynamic_analysis:
  features:  # Automatisch ergänzt mit _trend, _volatility, etc.
    - roa
    - roe
    - ebit_margin
    - revt
    - debt_to_equity
    - fcf  # NEU: Free Cash Flow
    - capex  # NEU: Capital Expenditures

combined_analysis:
  features_static:
    - roa
    - roe
    - ebit_margin
    - gross_margin
    - fcf_margin
    - current_ratio
    - debt_to_equity
    - financial_leverage

  features_dynamic:
    - roa_trend
    - margin_trend
    - leverage_trend
    - revenue_growth
    - fcf_growth
    - margin_volatility
    - growth_quality

# ========================================
# DATA & MARKET SETTINGS
# ========================================
data:
  market: 'germany'  # oder 'auto' für automatische Erkennung
  input_dir: 'data/raw'
  output_dir: 'output'

# ========================================
# GLOBAL SETTINGS
# ========================================
global:
  random_state: 42

output:
  create_plots: true
  create_company_lists: true

# ========================================
# INTERACTIVE MODE PRESETS
# ========================================
# Diese Presets können im Interactive Mode ausgewählt werden
# Du kannst die Presets hier anpassen für deine bevorzugten Setups
interactive:
  presets:
    quick_test:
      name: "Quick Test"
      description: "Schneller Test mit K-Means, nur Static, keine Plots"
      algorithms:
        - kmeans
      analyses:
        - static
      kmeans_mode: comparative
      skip_preprocessing: true
      create_plots: false
      comparison_mode: false

    full_analysis:
      name: "Full Analysis"
      description: "Komplette Analyse mit allen Algorithmen und Modi"
      algorithms:
        - kmeans
        - hierarchical
        - dbscan
      analyses:
        - static
        - dynamic
        - combined
      kmeans_mode: both  # comparative + hierarchical
      hierarchical_mode: hierarchical
      dbscan_mode: hierarchical
      skip_preprocessing: false
      create_plots: true
      comparison_mode: true

    comparison_mode:
      name: "Comparison Mode"
      description: "Vergleich aller Algorithmen (nur Combined)"
      algorithms:
        - kmeans
        - hierarchical
        - dbscan
      analyses:
        - combined
      kmeans_mode: hierarchical
      hierarchical_mode: hierarchical
      dbscan_mode: hierarchical
      skip_preprocessing: true
      create_plots: false
      comparison_mode: true

    kmeans_exploration:
      name: "K-Means Exploration"
      description: "Vergleich beider K-Means Modi (Comparative vs Hierarchical)"
      algorithms:
        - kmeans
      analyses:
        - static
        - dynamic
        - combined
      kmeans_mode: both
      skip_preprocessing: true
      create_plots: true
      comparison_mode: false

    dbscan_tuning:
      name: "DBSCAN Tuning"
      description: "DBSCAN mit Parameter-Tuning bei Problemen"
      algorithms:
        - dbscan
      analyses:
        - static
        - dynamic
        - combined
      dbscan_mode: hierarchical
      skip_preprocessing: true
      create_plots: false
      comparison_mode: false
      auto_tune_dbscan: true  # Fragt bei >50% Noise nach Parameter-Anpassung
